name: "hrelementary"
version: "0.0.1"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
profile: "hrelementary"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-end:
  - "{{ hrelementary.on_run_end(results) }}"
